services:
    app:
        image: analytics-api:v1
        build:
            context: .
            dockerfile: Dockerfile
        # environment:
        #     - PORT=8002
        #     - DATABASE_URL=postgresql+psycopg://time-user:time-pw@db_service:5432/timescaledb
        env_file:
            - .env.compose
        ports:
            - "8080:80"
        commands: uvicorn main:app --host 0.0.0.0 --port 8002 --reload
        volumes:
            - ./src:/code:rw
        develop:
            watch:
                - action: rebuild
                  path: Dockerfile
                - action: rebuild
                  path: requirements.txt
                - action: rebuild
                  path: compose.yml
    # postgresql+psycopg://time-user:time-pw@hostvalue:5432/timescaledb
    db_service:
        image: timescale/timescaledb:latest-pg17
        environment:
            - POSTGRES_USER=time-user
            - POSTGRES_PASSWORD=time-pw
            - POSTGRES_DB=tiemscaledb
        ports:
            - "5432:5432"
        expose:
            - 5432
        volumes:
            - timescaledb_data:/var/lib/postgresql/data

volumes: timescaledb_data
